### ISSUE TITLE
BBox offset

### ISSUE THREAD

**Issue by xiedidan** [EmmanuelMess/BoundingBoxMinecraftMod#1]
Hi, thanks for sharing this great mod. I've managed to deploy it on my own machine. However, I found the bboxes are not very accurate, as we can see from the snapshot in readme.  
I tried to lower [scan steps](https://github.com/EmmanuelMess/BoundingBoxMinecraftMod/blob/629c0b0bed8648d7cc2d4d35ef0a5d221394a113/src/main/java/net/fabricmc/example/ExampleMod.java#L72) from 2 to 1. Results are better but still not perfect.  
I know this mod is mainly based on [fabric pixel raycast tutorial](https://fabricmc.net/wiki/tutorial:pixel_raycast), but I don't quite understand the calculations. Is there any chance to improve the bbox accuracy?

**Comment by EmmanuelMess** [comment]
What's your resolution? What are your requirements? Can you send a screenshot of your worst case scenario?

Note: if you'd prefer we can talk over at the telegram for my apps: t.me/EmmanuelsApps
